# Generated by Django 5.0 on 2023-12-07 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestador_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagens', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_chats', to=settings.AUTH_USER_MODEL)),
                ('prestador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestador_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_servicos', models.IntegerField()),
                ('num_solicitacoes', models.IntegerField()),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carteira_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='app.carteira')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField()),
                ('metodo', models.CharField(max_length=255)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_cliente', to=settings.AUTH_USER_MODEL)),
                ('prestador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_prestador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(max_length=255)),
                ('ramo', models.CharField(max_length=255)),
                ('num_servicos', models.IntegerField()),
                ('num_solicitacoes', models.IntegerField()),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('pontuacao', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliado_reviews', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('pagamento_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servico_pagamento', to='app.pagamento')),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='servico_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='app.servico'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora_solicitacao', models.DateTimeField()),
                ('data_hora_servico', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cliente', to=settings.AUTH_USER_MODEL)),
                ('prestador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_prestador', to=settings.AUTH_USER_MODEL)),
                ('servico_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_servico', to='app.servico')),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='solicitacao_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='app.solicitacao'),
        ),
    ]
